### ISSUE TITLE
wps签到报错

### ISSUE THREAD

**Issue by CharliesTONG** [ytt447735/automation#27]
出错了！详细错误👇错误CK👉wpsua=xxxxxxxxxxxxxxxxxxxxxxxxxx;wps_sid=xxxxxxxxxxxxxxxxxxxxx
错误内容:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
PUSHPLUS 服务启动
PUSHPLUS 推送成功！

这个是什么原因

**Comment by ytt447735** [comment]
打码服务器压力有点大，打算关停，自行部署吧

**Comment by CharliesTONG** [comment]
> 打码服务器压力有点大，打算关停，自行部署吧
![屏幕截图 2024-12-09 092021](https://github.com/user-attachments/assets/db44c2a2-b9d6-4134-9c68-a6d5d9155599)
部署完docker，8080访问为hello world，如上图替换的链接，报下述错误

出错了！详细错误👇错误CK👉wpsua=xxxxxxxxxxxxxxxxxxxxxxxxxx;wps_sid=xxxxxxxxxxxxxxxxxxxxx
list index out of range
WPS_PC

**Comment by Aaronchannn** [comment]
> > 打码服务器压力有点大，打算关停，自行部署吧
> > ![屏幕截图 2024-12-09 092021](https://private-user-images.githubusercontent.com/61494189/393663115-db44c2a2-b9d6-4134-9c68-a6d5d9155599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzY5MzEsIm5iZiI6MTczMzczNjYzMSwicGF0aCI6Ii82MTQ5NDE4OS8zOTM2NjMxMTUtZGI0NGMyYTItYjlkNi00MTM0LTljNjgtYTZkNWQ5MTU1NTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5MzAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZjBmYzA2YzlkNjAzNjNlMjc5NTQ2ODA5ODVkNzhiZmQyYWIyNmZlZGQ1YjI3NGZjNTUwNTk0ODg1NTY2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2EY5hXmnp1XGW1tIYtjxlsnKGX43pHPUCjU_1eCShvU)
> > 部署完docker，8080访问为hello world，如上图替换的链接，报下述错误
> 
> 出错了！详细错误👇错误CK👉wpsua=xxxxxxxxxxxxxxxxxxxxxxxxxx;wps_sid=xxxxxxxxxxxxxxxxxxxxx list index out of range WPS_PC

同样情况+1

**Comment by ytt447735** [comment]
没有详细日志我也不知道你们这是啥问题

**Comment by Aaronchannn** [comment]
> > 没有详细日志我也不知道你们这是啥问题
> 
> 详细日志在哪里看

我这拉取最新代码就可以了

**Comment by CharliesTONG** [comment]
> > > 没有详细日志我也不知道你们这是啥问题
> > 
> > 
> > 详细日志在哪里看
> 
> 我这拉取最新代码就可以了

还是一样的

**Comment by Aaronchannn** [comment]
> > > > 没有详细日志我也不知道你们这是啥问题
> > > 
> > > 
> > > 详细日志在哪里看
> > 
> > 
> > 我这拉取最新代码就可以了
> 
> 还是一样的

试试脚本容器内能不能ping通192.168.2.161

**Comment by CharliesTONG** [comment]
> > > > > 没有详细日志我也不知道你们这是啥问题
> > > > 
> > > > 
> > > > 详细日志在哪里看
> > > 
> > > 
> > > 我这拉取最新代码就可以了
> > 
> > 
> > 还是一样的
> 
> 试试脚本容器内能不能ping通192.168.2.161

可以ping通

**Comment by Yxini-p** [comment]
-------------------总共1个wps_PC CK-------------------
{"account":"","account_num":1,"address":"","city":"","companyid":0,"country":"","current_companyid":0,"departmentid":"","email":"","firstname":"","is_company_account":false,"is_plus":true,"lastname":"","loginmode":"phone_sms:+86***730","nickname":"Yxin","phonenumber":"176***730","pic":"https://img.qwps.cn/77d104c07b2a4bc69b7fc9bac2d56406?imageMogr2/thumbnail/180x180!","postal":"","province":"","regtime":1540968230,"result":"ok","role":["user"],"sex":"","status":"active","userid":422685704,"uzone":"CN-HN"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 365, in <module>
    r.run()
  File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 336, in run
    if self.code_processing():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 159, in code_processing
    co = code.identify('pc', image_base64, '0')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/ytt447735_automation_main/fun/code.py", line 16, in identify
    response = requests.request("POST", url, headers=headers, data=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

## 执行结束... 2024-12-14 16:43:05  耗时 1 秒

**Comment by drw2005** [comment]
> -------------------总共1个wps_PC CK------------------- {"account":"","account_num":1,"address":"","city":"","companyid":0,"country":"","current_companyid":0,"departmentid":"","email":"","firstname":"","is_company_account":false,"is_plus":true,"lastname":"","loginmode":"phone_sms:+86_**730","nickname":"Yxin","phonenumber":"176**_730","pic":"[https://img.qwps.cn/77d104c07b2a4bc69b7fc9bac2d56406?imageMogr2/thumbnail/180x180!","postal":"","province":"","regtime":1540968230,"result":"ok","role":["user"],"sex":"","status":"active","userid":422685704,"uzone":"CN-HN"}](https://img.qwps.cn/77d104c07b2a4bc69b7fc9bac2d56406?imageMogr2/thumbnail/180x180!%22,%22postal%22:%22%22,%22province%22:%22%22,%22regtime%22:1540968230,%22result%22:%22ok%22,%22role%22:%5B%22user%22%5D,%22sex%22:%22%22,%22status%22:%22active%22,%22userid%22:422685704,%22uzone%22:%22CN-HN%22%7D) Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen httplib_response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request httplib_response = conn.getresponse() ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse response.begin() File "/usr/local/lib/python3.11/http/client.py", line 325, in begin version, status, reason = self._read_status() ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status raise RemoteDisconnected("Remote end closed connection without" http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen retries = retries.increment( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 552, in increment raise six.reraise(type(error), error, _stacktrace) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise raise value.with_traceback(tb) File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 716, in urlopen httplib_response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 463, in _make_request httplib_response = conn.getresponse() ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse response.begin() File "/usr/local/lib/python3.11/http/client.py", line 325, in begin version, status, reason = self._read_status() ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status raise RemoteDisconnected("Remote end closed connection without" urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 365, in r.run() File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 336, in run if self.code_processing(): ^^^^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/ytt447735_automation_main/wpspc.py", line 159, in code_processing co = code.identify('pc', image_base64, '0') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/ql/data/scripts/ytt447735_automation_main/fun/code.py", line 16, in identify response = requests.request("POST", url, headers=headers, data=payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> 执行结束... 2024-12-14 16:43:05 耗时 1 秒　　　
> 
> 有人知道这是啥问题吗

同样的情况，你解决了没有？

**Comment by gaohan-cmd** [comment]
> > 打码服务器压力有点大，打算关停，自行部署吧
> > ![屏幕截图 2024-12-09 092021](https://github.com/user-attachments/assets/db44c2a2-b9d6-4134-9c68-a6d5d9155599)
> > 部署完docker，8080访问为hello world，如上图替换的链接，报下述错误
> 
> 出错了！详细错误👇错误CK👉wpsua=xxxxxxxxxxxxxxxxxxxxxxxxxx;wps_sid=xxxxxxxxxxxxxxxxxxxxx list index out of range WPS_PC

最新代码，同样报错
